// page
export const ON_PROCESS_PAGE_LOADING = 'ON_PROCESS_PAGE_LOADING';
export const ON_PROCESS_PAGE_ERROR = 'ON_PROCESS_PAGE_ERROR';

// podcast
export const GET_ALL_PODCASTS = 'GET_ALL_PODCASTS';
export const GET_SINGLE_PODCAST = 'GET_SINGLE_PODCAST';
export const ON_FILTER_PODCASTS = 'ON_FILTER_PODCASTS';

export const ON_PROCESS_PODCASTS_REQUEST = 'ON_PROCESS_PODCASTS_REQUEST';
export const ON_PODCASTS_REQUEST_SUCCESS = 'ON_PODCASTS_REQUEST_SUCCESS';
export const ON_PODCASTS_REQUEST_FAILURE = 'ON_PODCASTS_REQUEST_FAILURE';


